name: Feature Request
description: Suggest a new skill or enhancement
title: "[Feature]: "
labels: ["feature", "enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: I need to... or Currently I can't...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: Add a skill that... or Enhance the skill to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature?
      options:
        - New Skill
        - Skill Enhancement
        - Repository Infrastructure
        - Documentation
        - Testing/CI
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you tried?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Mockups / Screenshots (optional)
      description: Attach zero or more reference images by dragging files into this field.
      placeholder: Paste or drag-and-drop any number of screenshots, mockups, or diagrams here.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context?
    validations:
      required: false
